// <auto-generated />
using System;
using Atracciones.Backend.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atracciones.Backend.DataAccess.Migrations
{
    [DbContext(typeof(AtraccionesDbContext))]
    [Migration("20260424025241_FixBridge2")]
    partial class FixBridge2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Atraccion", b =>
                {
                    b.Property<int>("AtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("at_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AtId"));

                    b.Property<string>("AtDescripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("at_descripcion");

                    b.Property<string>("AtDireccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("at_direccion");

                    b.Property<bool>("AtDisponible")
                        .HasColumnType("boolean")
                        .HasColumnName("at_disponible");

                    b.Property<int?>("AtDuracionMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("at_duracion_minutos");

                    b.Property<string>("AtEstado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("at_estado");

                    b.Property<DateTime?>("AtFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at_fecha_eliminacion");

                    b.Property<DateTime>("AtFechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at_fecha_ingreso");

                    b.Property<DateTime?>("AtFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at_fecha_mod");

                    b.Property<string>("AtGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("at_guid");

                    b.Property<bool>("AtIncluyeAcompaniante")
                        .HasColumnType("boolean")
                        .HasColumnName("at_incluye_acompaniante");

                    b.Property<bool>("AtIncluyeTransporte")
                        .HasColumnType("boolean")
                        .HasColumnName("at_incluye_transporte");

                    b.Property<string>("AtIpEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("at_ip_eliminacion");

                    b.Property<string>("AtIpIngreso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("at_ip_ingreso");

                    b.Property<string>("AtIpMod")
                        .HasColumnType("text")
                        .HasColumnName("at_ip_mod");

                    b.Property<string>("AtNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("at_nombre");

                    b.Property<string>("AtNumEstablecimiento")
                        .HasColumnType("text")
                        .HasColumnName("at_num_establecimiento");

                    b.Property<decimal?>("AtPrecioReferencia")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("at_precio_referencia");

                    b.Property<string>("AtPuntoEncuentro")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("at_punto_encuentro");

                    b.Property<int>("AtTotalResenias")
                        .HasColumnType("integer")
                        .HasColumnName("at_total_resenias");

                    b.Property<string>("AtUsuarioEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("at_usuario_eliminacion");

                    b.Property<string>("AtUsuarioIngreso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("at_usuario_ingreso");

                    b.Property<string>("AtUsuarioMod")
                        .HasColumnType("text")
                        .HasColumnName("at_usuario_mod");

                    b.Property<int>("DesId")
                        .HasColumnType("integer")
                        .HasColumnName("des_id");

                    b.HasKey("AtId");

                    b.HasIndex("DesId");

                    b.ToTable("ATRACCION", (string)null);
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Categoria", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cat_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CatId"));

                    b.Property<string>("CatEstado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cat_estado");

                    b.Property<DateTime?>("CatFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cat_fecha_eliminacion");

                    b.Property<DateTime>("CatFechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cat_fecha_ingreso");

                    b.Property<DateTime?>("CatFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cat_fecha_mod");

                    b.Property<string>("CatGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cat_guid");

                    b.Property<string>("CatIpEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("cat_ip_eliminacion");

                    b.Property<string>("CatIpIngreso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cat_ip_ingreso");

                    b.Property<string>("CatIpMod")
                        .HasColumnType("text")
                        .HasColumnName("cat_ip_mod");

                    b.Property<string>("CatNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cat_nombre");

                    b.Property<int?>("CatParentId")
                        .HasColumnType("integer")
                        .HasColumnName("cat_parent_id");

                    b.Property<string>("CatUsuarioEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("cat_usuario_eliminacion");

                    b.Property<string>("CatUsuarioIngreso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cat_usuario_ingreso");

                    b.Property<string>("CatUsuarioMod")
                        .HasColumnType("text")
                        .HasColumnName("cat_usuario_mod");

                    b.HasKey("CatId");

                    b.HasIndex("CatParentId");

                    b.ToTable("CATEGORIA", (string)null);
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.CategoriaAtraccion", b =>
                {
                    b.Property<int>("CatId")
                        .HasColumnType("integer")
                        .HasColumnName("cat_id");

                    b.Property<int>("AtId")
                        .HasColumnType("integer")
                        .HasColumnName("at_id");

                    b.HasKey("CatId", "AtId");

                    b.HasIndex("AtId");

                    b.ToTable("CATEGORIA_ATRACCION", (string)null);
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Cliente", b =>
                {
                    b.Property<int>("CliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cli_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CliId"));

                    b.Property<string>("CliApellidos")
                        .HasColumnType("text")
                        .HasColumnName("cli_apellidos");

                    b.Property<string>("CliCorreo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("cli_correo");

                    b.Property<string>("CliDireccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("cli_direccion");

                    b.Property<string>("CliEstado")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("cli_estado");

                    b.Property<DateTime?>("CliFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cli_fecha_eliminacion");

                    b.Property<DateTime>("CliFechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cli_fecha_ingreso");

                    b.Property<string>("CliGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cli_guid");

                    b.Property<string>("CliIpEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("cli_ip_eliminacion");

                    b.Property<string>("CliIpIngreso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cli_ip_ingreso");

                    b.Property<string>("CliNombres")
                        .HasColumnType("text")
                        .HasColumnName("cli_nombres");

                    b.Property<string>("CliNumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cli_numero_identificacion");

                    b.Property<string>("CliTelefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cli_telefono");

                    b.Property<string>("CliTipoIdentificacion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cli_tipo_identificacion");

                    b.Property<string>("CliUsuarioEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("cli_usuario_eliminacion");

                    b.Property<string>("CliUsuarioIngreso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cli_usuario_ingreso");

                    b.Property<int?>("UsuId")
                        .HasColumnType("integer")
                        .HasColumnName("usu_id");

                    b.HasKey("CliId");

                    b.HasIndex("UsuId");

                    b.ToTable("CLIENTES", (string)null);
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.DatosFacturacion", b =>
                {
                    b.Property<int>("DfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("dfac_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DfId"));

                    b.Property<string>("DfApellido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dfac_apellido");

                    b.Property<string>("DfCorreo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dfac_correo");

                    b.Property<DateTime>("DfFechaIngreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DfGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dfac_guid");

                    b.Property<string>("DfNombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dfac_nombre");

                    b.Property<string>("DfTelefono")
                        .HasColumnType("text")
                        .HasColumnName("dfac_telefono");

                    b.Property<int>("FacId")
                        .HasColumnType("integer")
                        .HasColumnName("fac_id");

                    b.HasKey("DfId");

                    b.HasIndex("FacId")
                        .IsUnique();

                    b.ToTable("DATOS_FACTURACION", (string)null);
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Destino", b =>
                {
                    b.Property<int>("DesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("des_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DesId"));

                    b.Property<string>("DesEstado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("des_estado");

                    b.Property<DateTime?>("DesFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("des_fecha_eliminacion");

                    b.Property<DateTime>("DesFechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("des_fecha_ingreso");

                    b.Property<DateTime?>("DesFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("des_fecha_mod");

                    b.Property<string>("DesGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("des_guid");

                    b.Property<string>("DesImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("des_imagen_url");

                    b.Property<string>("DesIpEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("des_ip_eliminacion");

                    b.Property<string>("DesIpIngreso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("des_ip_ingreso");

                    b.Property<string>("DesIpMod")
                        .HasColumnType("text")
                        .HasColumnName("des_ip_mod");

                    b.Property<string>("DesNombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("des_nombre");

                    b.Property<string>("DesPais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("des_pais");

                    b.Property<string>("DesUsuarioEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("des_usuario_eliminacion");

                    b.Property<string>("DesUsuarioIngreso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("des_usuario_ingreso");

                    b.Property<string>("DesUsuarioMod")
                        .HasColumnType("text")
                        .HasColumnName("des_usuario_mod");

                    b.HasKey("DesId");

                    b.ToTable("DESTINO", (string)null);
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.DetalleReserva", b =>
                {
                    b.Property<int>("DetResId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rdet_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetResId"));

                    b.Property<int>("DetCantidad")
                        .HasColumnType("integer")
                        .HasColumnName("rdet_cantidad");

                    b.Property<decimal>("DetPrecioUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("rdet_precio_unit");

                    b.Property<string>("DetResGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rdet_guid");

                    b.Property<decimal>("DetSubtotal")
                        .HasColumnType("numeric")
                        .HasColumnName("rdet_subtotal");

                    b.Property<string>("DetTitulo")
                        .HasColumnType("text")
                        .HasColumnName("rdet_titulo");

                    b.Property<int>("ResId")
                        .HasColumnType("integer")
                        .HasColumnName("rev_id");

                    b.Property<int>("TicId")
                        .HasColumnType("integer")
                        .HasColumnName("tck_id");

                    b.HasKey("DetResId");

                    b.HasIndex("ResId");

                    b.HasIndex("TicId");

                    b.ToTable("RESERVA_DETALLE", (string)null);
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Factura", b =>
                {
                    b.Property<int>("FacId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("fac_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FacId"));

                    b.Property<string>("FacEstado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("fac_estado");

                    b.Property<DateTime?>("FacFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fac_fecha_eliminacion");

                    b.Property<DateTime>("FacFechaEmision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fac_fecha_emision");

                    b.Property<DateTime?>("FacFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fac_fecha_mod");

                    b.Property<string>("FacGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fac_guid");

                    b.Property<string>("FacIpEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("fac_ip_eliminacion");

                    b.Property<string>("FacIpIngreso")
                        .HasColumnType("text")
                        .HasColumnName("fac_ip_ingreso");

                    b.Property<string>("FacIpMod")
                        .HasColumnType("text")
                        .HasColumnName("fac_ip_mod");

                    b.Property<string>("FacNumero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fac_numero");

                    b.Property<string>("FacObservacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fac_observacion");

                    b.Property<string>("FacOrigenCanal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fac_origen_canal");

                    b.Property<decimal>("FacTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("fac_total");

                    b.Property<string>("FacUsuarioEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("fac_usuario_eliminacion");

                    b.Property<string>("FacUsuarioIngreso")
                        .HasColumnType("text")
                        .HasColumnName("fac_usuario_ingreso");

                    b.Property<string>("FacUsuarioMod")
                        .HasColumnType("text")
                        .HasColumnName("fac_usuario_mod");

                    b.Property<int>("RevId")
                        .HasColumnType("integer")
                        .HasColumnName("rev_id");

                    b.HasKey("FacId");

                    b.HasIndex("RevId")
                        .IsUnique();

                    b.ToTable("FACTURAS", (string)null);
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Idioma", b =>
                {
                    b.Property<int>("IdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdId"));

                    b.Property<string>("IdCodigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("id_guid");

                    b.Property<string>("IdEstado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_estado");

                    b.Property<string>("IdNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_descripcion");

                    b.HasKey("IdId");

                    b.ToTable("IDIOMA", (string)null);
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.IdiomaAtraccion", b =>
                {
                    b.Property<int>("IdId")
                        .HasColumnType("integer")
                        .HasColumnName("id_id");

                    b.Property<int>("AtId")
                        .HasColumnType("integer")
                        .HasColumnName("at_id");

                    b.Property<int?>("AtraccionAtId")
                        .HasColumnType("integer");

                    b.HasKey("IdId", "AtId");

                    b.HasIndex("AtId");

                    b.HasIndex("AtraccionAtId");

                    b.ToTable("IDIOMA_ATRACCION", (string)null);
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Imagen", b =>
                {
                    b.Property<int>("ImgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("img_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImgId"));

                    b.Property<int>("AtId")
                        .HasColumnType("integer")
                        .HasColumnName("at_id");

                    b.Property<string>("ImgDescripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("img_descripcion");

                    b.Property<string>("ImgEstado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("img_estado");

                    b.Property<DateTime?>("ImgFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("img_fecha_eliminacion");

                    b.Property<DateTime>("ImgFechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("img_fecha_ingreso");

                    b.Property<DateTime?>("ImgFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("img_fecha_mod");

                    b.Property<string>("ImgGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("img_guid");

                    b.Property<string>("ImgIpEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("img_ip_eliminacion");

                    b.Property<string>("ImgIpIngreso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("img_ip_ingreso");

                    b.Property<string>("ImgIpMod")
                        .HasColumnType("text")
                        .HasColumnName("img_ip_mod");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("img_url");

                    b.Property<string>("ImgUsuarioEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("img_usuario_eliminacion");

                    b.Property<string>("ImgUsuarioIngreso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("img_usuario_ingreso");

                    b.Property<string>("ImgUsuarioMod")
                        .HasColumnType("text")
                        .HasColumnName("img_usuario_mod");

                    b.HasKey("ImgId");

                    b.HasIndex("AtId");

                    b.ToTable("IMAGEN", (string)null);
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Incluye", b =>
                {
                    b.Property<int>("IncId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("inc_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IncId"));

                    b.Property<string>("IncDescripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("inc_descripcion");

                    b.Property<string>("IncEstado")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("inc_estado");

                    b.Property<string>("IncGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("inc_guid");

                    b.HasKey("IncId");

                    b.ToTable("INCLUYE", (string)null);
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.IncluyeAtraccion", b =>
                {
                    b.Property<int>("IncId")
                        .HasColumnType("integer")
                        .HasColumnName("inc_id");

                    b.Property<int>("AtId")
                        .HasColumnType("integer")
                        .HasColumnName("at_id");

                    b.Property<int?>("AtraccionAtId")
                        .HasColumnType("integer");

                    b.HasKey("IncId", "AtId");

                    b.HasIndex("AtId");

                    b.HasIndex("AtraccionAtId");

                    b.ToTable("ATRACCION_INCLUYE", (string)null);
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.LogAuditoria", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LogId"));

                    b.Property<string>("LogDatosAnteriores")
                        .HasColumnType("text")
                        .HasColumnName("log_datos_anteriores");

                    b.Property<string>("LogDatosNuevos")
                        .HasColumnType("text")
                        .HasColumnName("log_datos_nuevos");

                    b.Property<DateTime>("LogFechaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("log_fecha_utc");

                    b.Property<string>("LogGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("log_guid");

                    b.Property<string>("LogIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("log_ip");

                    b.Property<string>("LogOperacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("log_operacion");

                    b.Property<string>("LogOrigenCanal")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("log_origen_canal");

                    b.Property<string>("LogRegistroGuid")
                        .HasColumnType("text")
                        .HasColumnName("log_registro_guid");

                    b.Property<int?>("LogRegistroId")
                        .HasColumnType("integer")
                        .HasColumnName("log_registro_id");

                    b.Property<string>("LogTabla")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("log_tabla");

                    b.Property<string>("LogUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("log_usuario");

                    b.HasKey("LogId");

                    b.ToTable("AUDITORIA_LOG", (string)null);
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Resena", b =>
                {
                    b.Property<int>("ResenaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rsn_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResenaId"));

                    b.Property<int>("AtId")
                        .HasColumnType("integer")
                        .HasColumnName("at_id");

                    b.Property<int>("CliId")
                        .HasColumnType("integer")
                        .HasColumnName("cli_id");

                    b.Property<int>("ClienteCliId")
                        .HasColumnType("integer");

                    b.Property<int>("ResenaCalificacion")
                        .HasColumnType("integer")
                        .HasColumnName("rsn_rating");

                    b.Property<string>("ResenaComentario")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rsn_comentario");

                    b.Property<string>("ResenaEstado")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("rsn_estado");

                    b.Property<DateTime>("ResenaFechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rsn_fecha_creacion");

                    b.Property<DateTime?>("ResenaFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rsn_fecha_eliminacion");

                    b.Property<DateTime?>("ResenaFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rsn_fecha_mod");

                    b.Property<string>("ResenaGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rsn_guid");

                    b.Property<string>("ResenaIpCreacion")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("rsn_ip_creacion");

                    b.Property<string>("ResenaIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("rsn_ip_eliminacion");

                    b.Property<string>("ResenaIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("rsn_ip_mod");

                    b.Property<string>("ResenaUsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rsn_usuario_creacion");

                    b.Property<string>("ResenaUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rsn_usuario_eliminacion");

                    b.Property<string>("ResenaUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rsn_usuario_mod");

                    b.Property<int?>("RevId")
                        .HasColumnType("integer")
                        .HasColumnName("rev_id");

                    b.HasKey("ResenaId");

                    b.HasIndex("AtId");

                    b.HasIndex("ClienteCliId");

                    b.HasIndex("RevId");

                    b.ToTable("RESENIA", (string)null);
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Reserva", b =>
                {
                    b.Property<int>("ResId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rev_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResId"));

                    b.Property<int>("CliId")
                        .HasColumnType("integer")
                        .HasColumnName("cli_id");

                    b.Property<int?>("ClienteCliId")
                        .HasColumnType("integer");

                    b.Property<string>("ResCodigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rev_codigo");

                    b.Property<string>("ResEstado")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("rev_estado");

                    b.Property<DateTime?>("ResFechaCancelacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rev_fecha_cancelacion");

                    b.Property<DateTime?>("ResFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rev_fecha_mod");

                    b.Property<DateTime>("ResFechaReservaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rev_fecha_reserva_utc");

                    b.Property<string>("ResGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rev_guid");

                    b.Property<string>("ResIpCancelacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("rev_ip_cancelacion");

                    b.Property<string>("ResIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("rev_ip_ingreso");

                    b.Property<string>("ResIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("rev_ip_mod");

                    b.Property<string>("ResMotivoCancelacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("rev_motivo_cancelacion");

                    b.Property<string>("ResOrigenCanal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rev_origen_canal");

                    b.Property<decimal>("ResSubtotal")
                        .HasColumnType("numeric")
                        .HasColumnName("rev_subtotal");

                    b.Property<decimal>("ResTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("rev_total");

                    b.Property<string>("ResUsuarioCancelacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rev_usuario_cancelacion");

                    b.Property<string>("ResUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rev_usuario_ingreso");

                    b.Property<string>("ResUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rev_usuario_mod");

                    b.Property<decimal>("ResValorIva")
                        .HasColumnType("numeric")
                        .HasColumnName("rev_valor_iva");

                    b.HasKey("ResId");

                    b.HasIndex("CliId");

                    b.HasIndex("ClienteCliId");

                    b.ToTable("RESERVAS", (string)null);
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolId"));

                    b.Property<string>("RolDescripcion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("rol_descripcion");

                    b.Property<string>("RolEstado")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("rol_estado");

                    b.Property<DateTime?>("RolFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rol_fecha_eliminacion");

                    b.Property<DateTime>("RolFechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rol_fecha_ingreso");

                    b.Property<string>("RolGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol_guid");

                    b.Property<string>("RolIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("rol_ip_eliminacion");

                    b.Property<string>("RolIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("rol_ip_ingreso");

                    b.Property<string>("RolUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rol_usuario_eliminacion");

                    b.Property<string>("RolUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rol_usuario_ingreso");

                    b.HasKey("RolId");

                    b.ToTable("ROLES", (string)null);
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Ticket", b =>
                {
                    b.Property<int>("TicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tck_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TicId"));

                    b.Property<int>("AtId")
                        .HasColumnType("integer")
                        .HasColumnName("at_id");

                    b.Property<int>("TicCapacidadMaxima")
                        .HasColumnType("integer")
                        .HasColumnName("tck_capacidad_maxima");

                    b.Property<int>("TicCuposDisponibles")
                        .HasColumnType("integer")
                        .HasColumnName("tck_cupos_disponibles");

                    b.Property<string>("TicEstado")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("tck_estado");

                    b.Property<DateTime?>("TicFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tck_fecha_eliminacion");

                    b.Property<DateTime>("TicFechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tck_fecha_ingreso");

                    b.Property<DateTime?>("TicFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tck_fecha_mod");

                    b.Property<string>("TicGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tck_guid");

                    b.Property<string>("TicIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("tck_ip_eliminacion");

                    b.Property<string>("TicIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("tck_ip_ingreso");

                    b.Property<string>("TicIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("tck_ip_mod");

                    b.Property<decimal>("TicPrecio")
                        .HasColumnType("numeric")
                        .HasColumnName("tck_precio");

                    b.Property<string>("TicTipoParticipante")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tck_tipo_participante");

                    b.Property<string>("TicTitulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("tck_titulo");

                    b.Property<string>("TicUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tck_usuario_eliminacion");

                    b.Property<string>("TicUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tck_usuario_ingreso");

                    b.Property<string>("TicUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tck_usuario_mod");

                    b.HasKey("TicId");

                    b.HasIndex("AtId");

                    b.ToTable("TICKET", (string)null);
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usu_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuId"));

                    b.Property<string>("UsuEstado")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("usu_estado");

                    b.Property<DateTime?>("UsuFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usu_fecha_eliminacion");

                    b.Property<DateTime?>("UsuFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usu_fecha_mod");

                    b.Property<DateTime>("UsuFechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usu_fecha_registro");

                    b.Property<string>("UsuGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usu_guid");

                    b.Property<string>("UsuIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("usu_ip_eliminacion");

                    b.Property<string>("UsuIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("usu_ip_mod");

                    b.Property<string>("UsuIpRegistro")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("usu_ip_registro");

                    b.Property<string>("UsuLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usu_login");

                    b.Property<string>("UsuPasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("usu_password_hash");

                    b.Property<string>("UsuUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usu_usuario_eliminacion");

                    b.Property<string>("UsuUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usu_usuario_mod");

                    b.Property<string>("UsuUsuarioRegistro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usu_usuario_registro");

                    b.HasKey("UsuId");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.UsuarioRol", b =>
                {
                    b.Property<int>("UsuRolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usu_rol_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuRolId"));

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.Property<int>("UsuId")
                        .HasColumnType("integer")
                        .HasColumnName("usu_id");

                    b.HasKey("UsuRolId");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuId");

                    b.ToTable("USUARIOXROLES", (string)null);
                });

            modelBuilder.Entity("Horario", b =>
                {
                    b.Property<int>("HorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("hor_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HorId"));

                    b.Property<int>("HorCuposDisponibles")
                        .HasColumnType("integer")
                        .HasColumnName("hor_cupos_disponibles");

                    b.Property<string>("HorEstado")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("hor_estado");

                    b.Property<DateTime>("HorFecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hor_fecha");

                    b.Property<DateTime?>("HorFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hor_fecha_eliminacion");

                    b.Property<DateTime>("HorFechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hor_fecha_ingreso");

                    b.Property<DateTime?>("HorFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hor_fecha_mod");

                    b.Property<string>("HorGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hor_guid");

                    b.Property<TimeSpan?>("HorHoraFin")
                        .HasColumnType("interval")
                        .HasColumnName("hor_hora_fin");

                    b.Property<TimeSpan>("HorHoraInicio")
                        .HasColumnType("interval")
                        .HasColumnName("hor_hora_inicio");

                    b.Property<string>("HorIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("hor_ip_eliminacion");

                    b.Property<string>("HorIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("hor_ip_ingreso");

                    b.Property<string>("HorIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("hor_ip_mod");

                    b.Property<string>("HorUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hor_usuario_eliminacion");

                    b.Property<string>("HorUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hor_usuario_ingreso");

                    b.Property<string>("HorUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hor_usuario_mod");

                    b.Property<int>("TicId")
                        .HasColumnType("integer")
                        .HasColumnName("tck_id");

                    b.HasKey("HorId");

                    b.HasIndex("HorGuid")
                        .IsUnique()
                        .HasDatabaseName("UK_HORARIO_guid");

                    b.HasIndex("TicId", "HorFecha", "HorHoraInicio")
                        .IsUnique()
                        .HasDatabaseName("UK_HORARIO_slot");

                    b.ToTable("HORARIO", (string)null);
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Atraccion", b =>
                {
                    b.HasOne("Atracciones.Backend.DataAccess.Entities.Destino", "Destino")
                        .WithMany("Atracciones")
                        .HasForeignKey("DesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destino");
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Categoria", b =>
                {
                    b.HasOne("Atracciones.Backend.DataAccess.Entities.Categoria", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("CatParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.CategoriaAtraccion", b =>
                {
                    b.HasOne("Atracciones.Backend.DataAccess.Entities.Atraccion", "Atraccion")
                        .WithMany("CategoriaAtracciones")
                        .HasForeignKey("AtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atracciones.Backend.DataAccess.Entities.Categoria", "Categoria")
                        .WithMany("CategoriaAtracciones")
                        .HasForeignKey("CatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Cliente", b =>
                {
                    b.HasOne("Atracciones.Backend.DataAccess.Entities.Usuario", "Usuario")
                        .WithMany("Clientes")
                        .HasForeignKey("UsuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.DatosFacturacion", b =>
                {
                    b.HasOne("Atracciones.Backend.DataAccess.Entities.Factura", "Factura")
                        .WithOne("DatosFacturacion")
                        .HasForeignKey("Atracciones.Backend.DataAccess.Entities.DatosFacturacion", "FacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.DetalleReserva", b =>
                {
                    b.HasOne("Atracciones.Backend.DataAccess.Entities.Reserva", "Reserva")
                        .WithMany("Detalles")
                        .HasForeignKey("ResId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atracciones.Backend.DataAccess.Entities.Ticket", "Ticket")
                        .WithMany("DetalleReserva")
                        .HasForeignKey("TicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reserva");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Factura", b =>
                {
                    b.HasOne("Atracciones.Backend.DataAccess.Entities.Reserva", "Reserva")
                        .WithOne("Factura")
                        .HasForeignKey("Atracciones.Backend.DataAccess.Entities.Factura", "RevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.IdiomaAtraccion", b =>
                {
                    b.HasOne("Atracciones.Backend.DataAccess.Entities.Atraccion", "Atraccion")
                        .WithMany()
                        .HasForeignKey("AtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atracciones.Backend.DataAccess.Entities.Atraccion", null)
                        .WithMany("IdiomaAtracciones")
                        .HasForeignKey("AtraccionAtId");

                    b.HasOne("Atracciones.Backend.DataAccess.Entities.Idioma", "Idioma")
                        .WithMany("IdiomaAtracciones")
                        .HasForeignKey("IdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");

                    b.Navigation("Idioma");
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Imagen", b =>
                {
                    b.HasOne("Atracciones.Backend.DataAccess.Entities.Atraccion", "Atraccion")
                        .WithMany("Imagenes")
                        .HasForeignKey("AtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.IncluyeAtraccion", b =>
                {
                    b.HasOne("Atracciones.Backend.DataAccess.Entities.Atraccion", "Atraccion")
                        .WithMany()
                        .HasForeignKey("AtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atracciones.Backend.DataAccess.Entities.Atraccion", null)
                        .WithMany("IncluyeAtracciones")
                        .HasForeignKey("AtraccionAtId");

                    b.HasOne("Atracciones.Backend.DataAccess.Entities.Incluye", "Incluye")
                        .WithMany("IncluyeAtracciones")
                        .HasForeignKey("IncId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atraccion");

                    b.Navigation("Incluye");
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Resena", b =>
                {
                    b.HasOne("Atracciones.Backend.DataAccess.Entities.Atraccion", "Atraccion")
                        .WithMany()
                        .HasForeignKey("AtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atracciones.Backend.DataAccess.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteCliId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atracciones.Backend.DataAccess.Entities.Reserva", "Reserva")
                        .WithMany("Resenas")
                        .HasForeignKey("RevId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Atraccion");

                    b.Navigation("Cliente");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Reserva", b =>
                {
                    b.HasOne("Atracciones.Backend.DataAccess.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("CliId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atracciones.Backend.DataAccess.Entities.Cliente", null)
                        .WithMany("Reservas")
                        .HasForeignKey("ClienteCliId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Ticket", b =>
                {
                    b.HasOne("Atracciones.Backend.DataAccess.Entities.Atraccion", "Atraccion")
                        .WithMany("Tickets")
                        .HasForeignKey("AtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atraccion");
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.UsuarioRol", b =>
                {
                    b.HasOne("Atracciones.Backend.DataAccess.Entities.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Atracciones.Backend.DataAccess.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Horario", b =>
                {
                    b.HasOne("Atracciones.Backend.DataAccess.Entities.Ticket", "Ticket")
                        .WithMany("Horarios")
                        .HasForeignKey("TicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Atraccion", b =>
                {
                    b.Navigation("CategoriaAtracciones");

                    b.Navigation("IdiomaAtracciones");

                    b.Navigation("Imagenes");

                    b.Navigation("IncluyeAtracciones");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Categoria", b =>
                {
                    b.Navigation("CategoriaAtracciones");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Cliente", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Destino", b =>
                {
                    b.Navigation("Atracciones");
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Factura", b =>
                {
                    b.Navigation("DatosFacturacion")
                        .IsRequired();
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Idioma", b =>
                {
                    b.Navigation("IdiomaAtracciones");
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Incluye", b =>
                {
                    b.Navigation("IncluyeAtracciones");
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Reserva", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Factura");

                    b.Navigation("Resenas");
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Ticket", b =>
                {
                    b.Navigation("DetalleReserva");

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("Atracciones.Backend.DataAccess.Entities.Usuario", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
